version: '2'

services:
  crystal-methrics:
    image: jrei/crystal-alpine
    environment:
      - PORT=8000
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: tail -f /dev/null

  redis:
    image: redis
    ports:
      - 6379:6379

  logstash:
    image: logstash
    ports:
      - 8001:8001
    volumes:
      - ./misc/logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./misc/logstash/logstash.yml:/etc/logstash/logstash.yml
      - ./output:/app
    # command: tail -f /dev/null
    command: logstash -f /usr/share/logstash/config/logstash.conf

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 8000:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126




