version: '2'

services:
  crystal-methrics:
    build: .
    environment:
      - PORT=8000
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    volumes:
      - .:/app

  logstash:
    image: logstash
    ports:
      - 8001:8001
    volumes:
      - ./lib/logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./lib/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./output:/app
    # command: tail -f /dev/null
    command: logstash -f /usr/share/logstash/config/logstash.conf

  redis:
    image: redis
    ports:
      - 6379:6379


