version: '2'

services:
  crystal-methrics:
    build: .
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - .:/app

  logstash:
    image: logstash
    ports:
      - 8001:8001
    volumes:
      - ./SOMETHING

  redis:
    image: redis
    ports:
      - 6379:6379


